### ISSUE TITLE
Reverts on setUp()

### ISSUE THREAD

**Issue by shunkakinoki** [0xKitsune/Foundry-Huff#1]
Hi! Thank you for the wonderful repo
A newbie trying to learn solidity here
Getting the error below, running `forge test --ffi`
Would love to get help if possible 🙇‍♂️
```
No files changed, compilation skipped

Running 1 test for src/test/SimpleStore.t.sol:SimpleStoreTest
[FAIL. Reason: Setup failed: Revert] setUp() (gas: 0)
Traces:
  [13187] SimpleStoreTest::setUp() 
    ├─ [8170] HuffDeployer::deployContract("SimpleStore") 
    │   ├─ [0] VM::ffi(["huffc", "huff_contracts/SimpleStore.huff", "--bytecode -n"]) 
    │   │   └─ ← 0x
    │   └─ ← ()
    └─ ← ()

Test result: FAILED. 0 passed; 1 failed; finished in 1.29s

Failed tests:
[FAIL. Reason: Setup failed: Revert] setUp() (gas: 0)
```

**Comment by 0xKitsune** [comment]
Hey, I should have added a note regarding this before but I just added one to the readme temporarily.  

The HuffDeployer will not work until the [huffc yarn package](https://yarnpkg.com/package/huffc) is updated to include the [-n flag for compilation](https://github.com/huff-language/huffc/commit/2e5287afbfdf9cc977b204a4fd1e89c27375b040). Alternatively, you can build from source until then.  Once the yarn package is updated, I'll update the readme to remove the note after everything is functional.

**Comment by shunkakinoki** [comment]
Thank you for the explanation!
Excited for the rust rewrite too haha
