### ISSUE TITLE
How to deploy huff with constructor args

### ISSUE THREAD

**Issue by Tofunmi1** [0xKitsune/Foundry-Huff#2]
How to deploy huff with constructor args

**Comment by 0xKitsune** [comment]
Hey, there is no way right now to pass in constructor args, but will be easy to add. I have a few things going on this week but can probably update the repo this weekend so that you can pass in constructor args.

**Comment by 0xKitsune** [comment]
I just updated the repo so that you can pass in constructor args when deploying Huff contracts.

Now, when passing in constructor args, instead of using `huffDeployer.deployContract("SimpleStore")` you use `huffDeployer.deployContract("SimpleStore", abi.encode(arg0, arg1, arg2...))`

**Comment by Tofunmi1** [comment]
Cool,  thanks for this, I really appreciate
